# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
    name = "Packages"
    url = "/packages/"
    weight = 1
[[main]]
    name = "Installation"
    url = "/installation/"
    weight = 2
[[main]]
    name = "More"
    url = "/more/"
    weight = 3
[[main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
[[main]]
    pre = "<i class=\"fab fa-github fa-lg\"></i>"
    url = "https://github.com/tidymicrobiome/"
    weight = 5
    

