---
title: "Contact us"
date: "Created on 2022-09-09 and updated on `r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: false
  pdf_document:
    toc: false
pkgdown:
  as_is: false
---

```{r, include = FALSE, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  # fig.width = 7, 
  # fig.height = 5,
  warning = FALSE,
  message = TRUE,
  out.width = "100%"
)
```

# Citation

If you used `tidyMicrobiome` in your study, please cite the publication:

Shen, X., Yan, H., Wang, C. et al. TidyMass an object-oriented reproducible analysis framework for LC–MS data. Nat Commun 13, 4365 (2022). https://doi.org/10.1038/s41467-022-32155-w

Link: https://www.nature.com/articles/s41467-022-32155-w#citeas

---

# Contact

If you have any questions, please contact me.


<i class="fab fa-weixin fa-lg"></i> [shenxt1990](https://www.shenxt.info/files/wechat_QR.jpg)

<i class="fa fa-envelope"></i> shenxt@stanford.edu

<i class="fab fa-twitter fa-lg"></i> [Twitter](https://twitter.com/xiaotaoshen1990)

<i class="fa fa-map-marker-alt"></i> [M339, Alway Buidling, Cooper Lane, Palo Alto, CA 94304](https://www.google.com/maps/place/Alway+Building/@37.4322345,-122.1770883,17z/data=!3m1!4b1!4m5!3m4!1s0x808fa4d335c3be37:0x9057931f3b312c29!8m2!3d37.4322345!4d-122.1748996)

---

```{r, echo=FALSE}
# set seed for reproducible widget id
if (requireNamespace("htmltools", quietly = TRUE)) {
  htmlwidgets::setWidgetIdSeed(42)
}
library(leaflet)
leaflet::leaflet(width = "100%") %>%
  leaflet::addTiles() %>%
 leaflet::addMarkers(
    lng = -122.174878,
    lat = 37.432402,
    popup = "Stanford Medicine"
  )
```




